[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/.git/*"
  [headers.values]
    X-Frame-Options = "DENY"
    
[[redirects]]
  from = "/.git/*"
  to = "/404"
  status = 404
  force = true

[[redirects]]
  from = "/.env*"
  to = "/404"
  status = 404
  force = true
